// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_cr_d7GwhmjLMJJ0gUApRWmeIw24u4I',
    appId: '1:169486631197:web:9149c4f826884bf22da1f4',
    messagingSenderId: '169486631197',
    projectId: 'medical-appointments-8f543',
    authDomain: 'medical-appointments-8f543.firebaseapp.com',
    storageBucket: 'medical-appointments-8f543.appspot.com',
    measurementId: 'G-90YPSXDYBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaO0pmTdVju6CduTqxJdJdSUBK4jVQNB0',
    appId: '1:169486631197:android:b89ce9bdfbd03baa2da1f4',
    messagingSenderId: '169486631197',
    projectId: 'medical-appointments-8f543',
    storageBucket: 'medical-appointments-8f543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0_d7PiruhZwTxPZMorLxOXFtLNk6XsQ',
    appId: '1:169486631197:ios:a21959e8501cf5812da1f4',
    messagingSenderId: '169486631197',
    projectId: 'medical-appointments-8f543',
    storageBucket: 'medical-appointments-8f543.appspot.com',
    iosBundleId: 'com.example.graduateproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0_d7PiruhZwTxPZMorLxOXFtLNk6XsQ',
    appId: '1:169486631197:ios:a21959e8501cf5812da1f4',
    messagingSenderId: '169486631197',
    projectId: 'medical-appointments-8f543',
    storageBucket: 'medical-appointments-8f543.appspot.com',
    iosBundleId: 'com.example.graduateproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN_cr_d7GwhmjLMJJ0gUApRWmeIw24u4I',
    appId: '1:169486631197:web:a4ed60bbfd3d40192da1f4',
    messagingSenderId: '169486631197',
    projectId: 'medical-appointments-8f543',
    authDomain: 'medical-appointments-8f543.firebaseapp.com',
    storageBucket: 'medical-appointments-8f543.appspot.com',
    measurementId: 'G-Q1TBWPFE22',
  );

}